import { openDB, type DBSchema } from 'idb';
import { formatSurfaceLocation, type SurfaceLocation } from './location';

export type SurfaceMedia = { id: string; original: Blob; processed: Blob; createdAt: number; dateKey: string; timeLabel: string; locationLabel?: string; location?: SurfaceLocation; capture: boolean; pinIds?: string[]; originalPath?: string; processedPath?: string; remoteOnly?: boolean };
interface MediaDb extends DBSchema { media: { key: string; value: SurfaceMedia; indexes: { 'by-created': number } } }
const db = openDB<MediaDb>('surface-pwa-media', 1, { upgrade(database) { const store = database.createObjectStore('media', { keyPath: 'id' }); store.createIndex('by-created', 'createdAt'); } });
export async function listMedia(): Promise<SurfaceMedia[]> { return (await db).getAllFromIndex('media', 'by-created').then((items) => items.reverse()); }
export async function getMedia(id: string): Promise<SurfaceMedia | undefined> { return (await db).get('media', id); }
export async function saveMedia(file: Blob, location?: SurfaceLocation | null, capture = true): Promise<SurfaceMedia> { const now = Date.now(); const locationLabel = formatSurfaceLocation(location); const item: SurfaceMedia = { id: crypto.randomUUID(), original: file, processed: await burnSurfaceMetadata(file, locationLabel), createdAt: now, dateKey: new Date(now).toLocaleDateString('en-GB'), timeLabel: new Date(now).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }), locationLabel, location: location ?? undefined, capture, pinIds: [] }; await (await db).put('media', item); return item; }
export async function deleteMedia(id: string): Promise<void> { await (await db).delete('media', id); }
export async function putMedia(item: SurfaceMedia): Promise<void> { await (await db).put('media', item); }
export function objectUrl(blob: Blob): string { return URL.createObjectURL(blob); }
async function burnSurfaceMetadata(file: Blob, location: string): Promise<Blob> { try { const image = await createImageBitmap(file); const canvas = document.createElement('canvas'); canvas.width = image.width; canvas.height = image.height; const context = canvas.getContext('2d'); if (!context) return file; context.drawImage(image, 0, 0); const height = Math.max(64, Math.round(canvas.height * .12)); context.fillStyle = 'rgba(0,0,0,.58)'; context.fillRect(0, canvas.height - height, canvas.width, height); context.fillStyle = '#fff'; context.font = `${Math.max(14, Math.round(canvas.width / 34))}px sans-serif`; context.fillText(`${new Date().toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}  ${new Date().toLocaleDateString('en-GB')}`, 18, canvas.height - height + 24); if (location) context.fillText(location, 18, canvas.height - 16); return new Promise((resolve) => canvas.toBlob((blob) => resolve(blob ?? file), 'image/jpeg', .94)); } catch { return file; } }
